Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Layout/DotPosition:
  EnforcedStyle: trailing
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
  Enabled: true
AllCops:
  TargetRubyVersion: 2.4
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
